project_id = "enpovkaknaxfgzanyghn"

[functions.law-api]
verify_jwt = false

[functions.motif-api]
verify_jwt = false

[functions.image-api]
verify_jwt = false

[functions.web-search-api]
verify_jwt = false

[functions.weather-api]
verify_jwt = false

[functions.rag-admin-api]
verify_jwt = false

[functions.source-document-api]
verify_jwt = false
static_files = ["./functions/source-document-api/assets/*.enc"]
