#!/usr/bin/env python3
"""Encrypt downloadable source documents for authenticated Edge delivery."""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
from dataclasses import dataclass
from pathlib import Path

from cryptography.hazmat.primitives.ciphers.aead import AESGCM


MAGIC = b"HSD1"


@dataclass(frozen=True)
class DocumentSpec:
    document_id: str
    path: Path
    file_name: str
    media_type: str


def parse_document(value: str) -> DocumentSpec:
    parts = value.split("::")
    if len(parts) != 4:
        raise argparse.ArgumentTypeError("--document must be ID::PATH::FILENAME::MEDIA_TYPE")
    path = Path(parts[1]).expanduser().resolve()
    if not path.is_file():
        raise argparse.ArgumentTypeError(f"source document not found: {path}")
    document_id = parts[0].strip()
    if not document_id or not document_id.replace("-", "").isalnum():
        raise argparse.ArgumentTypeError("document id must contain only letters, numbers, and hyphens")
    requested_name = parts[2].strip()
    file_name = path.name if requested_name == "@basename" else requested_name
    return DocumentSpec(document_id, path, file_name, parts[3].strip())


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--document", action="append", type=parse_document, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--metadata", type=Path, required=True)
    parser.add_argument("--key-file", type=Path)
    args = parser.parse_args()
    key_text = args.key_file.read_text(encoding="utf-8").strip() if args.key_file else os.environ.get("SOURCE_DOCUMENT_KEY", "").strip()
    key = base64.b64decode(key_text, validate=True)
    if len(key) != 32:
        raise SystemExit("SOURCE_DOCUMENT_KEY must be a base64-encoded 32-byte key")
    if len({item.document_id for item in args.document}) != len(args.document):
        raise SystemExit("duplicate document id")
    args.output_dir.mkdir(parents=True, exist_ok=True)
    manifest = []
    for spec in args.document:
        plaintext = spec.path.read_bytes()
        nonce = os.urandom(12)
        aad = MAGIC + b":" + spec.document_id.encode("ascii")
        encrypted = AESGCM(key).encrypt(nonce, plaintext, aad)
        asset_name = f"{spec.document_id}.enc"
        package = MAGIC + nonce + encrypted
        (args.output_dir / asset_name).write_bytes(package)
        manifest.append({
            "id": spec.document_id,
            "fileName": spec.file_name,
            "mediaType": spec.media_type,
            "assetPath": f"./assets/{asset_name}",
            "size": len(plaintext),
            "plaintextSha256": hashlib.sha256(plaintext).hexdigest(),
            "encryptedSha256": hashlib.sha256(package).hexdigest(),
        })
    generated = "// Generated by scripts/encrypt-source-documents.py. Do not edit by hand.\n" + \
        "export const SOURCE_DOCUMENTS = " + json.dumps(manifest, ensure_ascii=False, separators=(",", ":")) + " as const;\n"
    args.manifest.write_text(generated, encoding="utf-8")
    metadata = {
        "schemaVersion": 1,
        "documentCount": len(manifest),
        "totalPlaintextBytes": sum(item["size"] for item in manifest),
        "documents": [{key: item[key] for key in ("id", "fileName", "size", "plaintextSha256", "encryptedSha256")} for item in manifest],
    }
    args.metadata.write_text(json.dumps(metadata, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({"documentCount": len(manifest), "totalPlaintextBytes": metadata["totalPlaintextBytes"]}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
