create table if not exists public.rag_chunk_overrides (
  id                  uuid primary key default gen_random_uuid(),
  base_chunk_id       text unique,
  document_title      text not null check (char_length(document_title) between 1 and 300),
  chapter_title       text not null default '' check (char_length(chapter_title) <= 500),
  section_title       text not null default '' check (char_length(section_title) <= 500),
  text                text not null check (char_length(text) between 1 and 20000),
  collection          text not null default 'admin-overlay' check (char_length(collection) <= 120),
  source_file         text not null default '' check (char_length(source_file) <= 500),
  revision_basis      text not null default '' check (char_length(revision_basis) <= 500),
  source_line_start   integer check (source_line_start is null or source_line_start > 0),
  source_line_end     integer check (source_line_end is null or source_line_end > 0),
  unit_type           text check (unit_type is null or char_length(unit_type) <= 80),
  related_regulations text[] not null default '{}',
  department          text check (department is null or char_length(department) <= 200),
  is_active           boolean not null default true,
  created_by_email    text not null,
  updated_by_email    text not null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index if not exists rag_chunk_overrides_document_idx
  on public.rag_chunk_overrides (document_title);
create index if not exists rag_chunk_overrides_updated_idx
  on public.rag_chunk_overrides (updated_at desc);

create table if not exists public.rag_chunk_override_revisions (
  id           bigint generated by default as identity primary key,
  override_id  uuid,
  action       text not null check (action in ('create', 'update', 'disable', 'restore', 'delete')),
  snapshot     jsonb not null,
  admin_email  text not null,
  created_at   timestamptz not null default now()
);

create index if not exists rag_chunk_override_revisions_lookup_idx
  on public.rag_chunk_override_revisions (override_id, created_at desc);

alter table public.rag_chunk_overrides enable row level security;
alter table public.rag_chunk_override_revisions enable row level security;

-- 브라우저 anon 키에는 정책을 부여하지 않는다. 관리 Edge Function의 service role만 접근한다.
revoke all on table public.rag_chunk_overrides from anon, authenticated;
revoke all on table public.rag_chunk_override_revisions from anon, authenticated;
revoke all on sequence public.rag_chunk_override_revisions_id_seq from anon, authenticated;
